package memory

import (
	"database/sql"
	"fmt"

	"agent-platform/internal/sqlitecontract"

	_ "modernc.org/sqlite"
)

func (s *SQLiteStore) initDB(startupAdopt bool) error {
	db, err := sql.Open("sqlite", s.dbPath)
	if err != nil {
		return err
	}
	s.db = db

	initialize := sqlitecontract.InitializeOrVerify
	if startupAdopt {
		initialize = sqlitecontract.InitializeOrVerifyAtStartup
	}
	return initialize(db, s.dbPath, s.root, memorySchemaSpec, func() (bool, error) {
		return sqlitecontract.HasResidualData(s.root)
	}, func() error {
		return createMemorySchema(db)
	})
}

func createMemorySchema(db *sql.DB) error {
	statements := []string{
		`CREATE TABLE IF NOT EXISTS MEMORIES (
			ID_ TEXT PRIMARY KEY,
			TS_ INTEGER NOT NULL,
			REQUEST_ID_ TEXT,
			CHAT_ID_ TEXT,
			AGENT_KEY_ TEXT NOT NULL DEFAULT '',
			SUBJECT_KEY_ TEXT NOT NULL DEFAULT '',
			SOURCE_TYPE_ TEXT NOT NULL DEFAULT '',
			SUMMARY_ TEXT NOT NULL DEFAULT '',
			CATEGORY_ TEXT DEFAULT 'general',
			IMPORTANCE_ INTEGER DEFAULT 5,
			TAGS_ TEXT,
			EMBEDDING_ BLOB,
			EMBEDDING_MODEL_ TEXT,
			UPDATED_AT_ INTEGER NOT NULL,
			ACCESS_COUNT_ INTEGER DEFAULT 0,
			LAST_ACCESSED_AT_ INTEGER,
			KIND_ TEXT NOT NULL DEFAULT 'fact',
			REF_ID_ TEXT NOT NULL DEFAULT '',
			SCOPE_TYPE_ TEXT NOT NULL DEFAULT 'agent',
			SCOPE_KEY_ TEXT NOT NULL DEFAULT '',
			TITLE_ TEXT NOT NULL DEFAULT '',
			CONFIDENCE_ REAL NOT NULL DEFAULT 0.9,
			STATUS_ TEXT NOT NULL DEFAULT 'active'
		)`,
		`CREATE TABLE IF NOT EXISTS MEMORY_FACTS (
			ID_ TEXT PRIMARY KEY,
			AGENT_KEY_ TEXT NOT NULL DEFAULT '',
			SCOPE_TYPE_ TEXT NOT NULL DEFAULT 'agent',
			SCOPE_KEY_ TEXT NOT NULL DEFAULT '',
			CATEGORY_ TEXT NOT NULL DEFAULT 'general',
			TITLE_ TEXT NOT NULL DEFAULT '',
			CONTENT_ TEXT NOT NULL DEFAULT '',
			TAGS_ TEXT NOT NULL DEFAULT '',
			IMPORTANCE_ INTEGER NOT NULL DEFAULT 5,
			CONFIDENCE_ REAL NOT NULL DEFAULT 0.9,
			STATUS_ TEXT NOT NULL DEFAULT 'active',
			SOURCE_KIND_ TEXT NOT NULL DEFAULT 'manual',
			SOURCE_REF_ TEXT NOT NULL DEFAULT '',
			DEDUPE_KEY_ TEXT NOT NULL DEFAULT '',
			CREATED_AT_ INTEGER NOT NULL,
			UPDATED_AT_ INTEGER NOT NULL,
			LAST_CONFIRMED_AT_ INTEGER,
			EXPIRES_AT_ INTEGER
		)`,
		`CREATE TABLE IF NOT EXISTS MEMORY_OBSERVATIONS (
			ID_ TEXT PRIMARY KEY,
			AGENT_KEY_ TEXT NOT NULL DEFAULT '',
			CHAT_ID_ TEXT NOT NULL DEFAULT '',
			RUN_ID_ TEXT NOT NULL DEFAULT '',
			SCOPE_TYPE_ TEXT NOT NULL DEFAULT 'chat',
			SCOPE_KEY_ TEXT NOT NULL DEFAULT '',
			TYPE_ TEXT NOT NULL DEFAULT 'discovery',
			TITLE_ TEXT NOT NULL DEFAULT '',
			SUMMARY_ TEXT NOT NULL DEFAULT '',
			DETAIL_ TEXT NOT NULL DEFAULT '',
			FILES_JSON_ TEXT NOT NULL DEFAULT '[]',
			TOOLS_JSON_ TEXT NOT NULL DEFAULT '[]',
			TAGS_ TEXT NOT NULL DEFAULT '',
			IMPORTANCE_ INTEGER NOT NULL DEFAULT 5,
			CONFIDENCE_ REAL NOT NULL DEFAULT 0.7,
			STATUS_ TEXT NOT NULL DEFAULT 'open',
			CREATED_AT_ INTEGER NOT NULL,
			UPDATED_AT_ INTEGER NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS MEMORY_LINKS (
			ID_ TEXT PRIMARY KEY,
			FROM_ID_ TEXT NOT NULL,
			TO_ID_ TEXT NOT NULL,
			RELATION_TYPE_ TEXT NOT NULL DEFAULT 'supports',
			WEIGHT_ REAL NOT NULL DEFAULT 1.0,
			CREATED_AT_ INTEGER NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS MEMORY_SNAPSHOTS (
			ID_ TEXT PRIMARY KEY,
			CHAT_ID_ TEXT NOT NULL,
			AGENT_KEY_ TEXT NOT NULL DEFAULT '',
			STABLE_ITEM_IDS_ TEXT NOT NULL DEFAULT '[]',
			OBSERVED_ITEM_IDS_ TEXT NOT NULL DEFAULT '[]',
			CREATED_AT_ INTEGER NOT NULL,
			UPDATED_AT_ INTEGER NOT NULL,
			UNIQUE(CHAT_ID_, AGENT_KEY_)
		)`,
		`CREATE TABLE IF NOT EXISTS MEMORY_HISTORY (
			ID_ TEXT PRIMARY KEY,
			TS_ INTEGER NOT NULL,
			AGENT_KEY_ TEXT NOT NULL DEFAULT '',
			CHAT_ID_ TEXT NOT NULL DEFAULT '',
			RUN_ID_ TEXT NOT NULL DEFAULT '',
			REQUEST_ID_ TEXT NOT NULL DEFAULT '',
			USER_KEY_ TEXT NOT NULL DEFAULT '',
			MEMORY_ID_ TEXT NOT NULL DEFAULT '',
			MEMORY_KIND_ TEXT NOT NULL DEFAULT '',
			SCOPE_TYPE_ TEXT NOT NULL DEFAULT '',
			SCOPE_KEY_ TEXT NOT NULL DEFAULT '',
			OPERATION_ TEXT NOT NULL,
			SOURCE_ TEXT NOT NULL DEFAULT '',
			STATUS_ TEXT NOT NULL DEFAULT 'ok',
			BEFORE_JSON_ TEXT NOT NULL DEFAULT '{}',
			AFTER_JSON_ TEXT NOT NULL DEFAULT '{}',
			DELTA_JSON_ TEXT NOT NULL DEFAULT '{}',
			META_JSON_ TEXT NOT NULL DEFAULT '{}'
		)`,
		`CREATE INDEX IF NOT EXISTS IDX_MEMORY_HISTORY_MEMORY_ID_TS ON MEMORY_HISTORY(MEMORY_ID_, TS_)`,
		`CREATE INDEX IF NOT EXISTS IDX_MEMORY_HISTORY_AGENT_TS ON MEMORY_HISTORY(AGENT_KEY_, TS_)`,
		`CREATE INDEX IF NOT EXISTS IDX_MEMORY_HISTORY_CHAT_TS ON MEMORY_HISTORY(CHAT_ID_, TS_)`,
		`CREATE INDEX IF NOT EXISTS IDX_MEMORY_HISTORY_OPERATION_TS ON MEMORY_HISTORY(OPERATION_, TS_)`,
		`CREATE INDEX IF NOT EXISTS IDX_MEMORY_HISTORY_RUN_TS ON MEMORY_HISTORY(RUN_ID_, TS_)`,
		`CREATE VIRTUAL TABLE IF NOT EXISTS MEMORIES_FTS USING fts5(
			SUMMARY_, SUBJECT_KEY_, CATEGORY_, TAGS_,
			content=MEMORIES, content_rowid=rowid
		)`,
		`CREATE TRIGGER IF NOT EXISTS MEMORIES_AI AFTER INSERT ON MEMORIES BEGIN
			INSERT INTO MEMORIES_FTS(rowid, SUMMARY_, SUBJECT_KEY_, CATEGORY_, TAGS_)
			VALUES (new.rowid, new.SUMMARY_, new.SUBJECT_KEY_, new.CATEGORY_, new.TAGS_);
		END`,
		`CREATE TRIGGER IF NOT EXISTS MEMORIES_AU AFTER UPDATE ON MEMORIES BEGIN
			INSERT INTO MEMORIES_FTS(MEMORIES_FTS, rowid, SUMMARY_, SUBJECT_KEY_, CATEGORY_, TAGS_)
			VALUES ('delete', old.rowid, old.SUMMARY_, old.SUBJECT_KEY_, old.CATEGORY_, old.TAGS_);
			INSERT INTO MEMORIES_FTS(rowid, SUMMARY_, SUBJECT_KEY_, CATEGORY_, TAGS_)
			VALUES (new.rowid, new.SUMMARY_, new.SUBJECT_KEY_, new.CATEGORY_, new.TAGS_);
		END`,
		`CREATE TRIGGER IF NOT EXISTS MEMORIES_AD AFTER DELETE ON MEMORIES BEGIN
			INSERT INTO MEMORIES_FTS(MEMORIES_FTS, rowid, SUMMARY_, SUBJECT_KEY_, CATEGORY_, TAGS_)
			VALUES ('delete', old.rowid, old.SUMMARY_, old.SUBJECT_KEY_, old.CATEGORY_, old.TAGS_);
		END`,
	}
	for _, stmt := range statements {
		if _, err := db.Exec(stmt); err != nil {
			return fmt.Errorf("init schema: %w", err)
		}
	}
	return nil
}

var memorySchemaSpec = sqlitecontract.Spec{
	Name:          "memory-v1",
	ApplicationID: 0x41504D4D, // APMM
	UserVersion:   1,
	Objects: []sqlitecontract.Object{
		{Type: "table", Name: "MEMORIES"},
		{Type: "table", Name: "MEMORY_FACTS"},
		{Type: "table", Name: "MEMORY_OBSERVATIONS"},
		{Type: "table", Name: "MEMORY_LINKS"},
		{Type: "table", Name: "MEMORY_SNAPSHOTS"},
		{Type: "table", Name: "MEMORY_HISTORY"},
		{Type: "table", Name: "MEMORIES_FTS"},
		{Type: "index", Name: "IDX_MEMORY_HISTORY_MEMORY_ID_TS"},
		{Type: "index", Name: "IDX_MEMORY_HISTORY_AGENT_TS"},
		{Type: "index", Name: "IDX_MEMORY_HISTORY_CHAT_TS"},
		{Type: "index", Name: "IDX_MEMORY_HISTORY_OPERATION_TS"},
		{Type: "index", Name: "IDX_MEMORY_HISTORY_RUN_TS"},
		{Type: "trigger", Name: "MEMORIES_AI"},
		{Type: "trigger", Name: "MEMORIES_AU"},
		{Type: "trigger", Name: "MEMORIES_AD"},
	},
	BuildCanonical: createMemorySchema,
}
