package apperrors

type Category string
type Scope string
type Code string

const (
	CategoryRequest    Category = "request"
	CategoryAuth       Category = "auth"
	CategoryProtocol   Category = "protocol"
	CategoryCatalog    Category = "catalog"
	CategoryChatRun    Category = "chat_run"
	CategoryModel      Category = "model"
	CategoryProxy      Category = "proxy"
	CategoryTool       Category = "tool"
	CategoryPolicy     Category = "policy"
	CategoryResource   Category = "resource"
	CategoryTerminal   Category = "terminal"
	CategoryMemory     Category = "memory"
	CategoryArchive    Category = "archive"
	CategoryAutomation Category = "automation"
	CategorySystem     Category = "system"
	CategoryTimeout    Category = "timeout"
	CategoryInterrupt  Category = "interrupt"
)

const (
	ScopeRequest        Scope = "request"
	ScopeConnection     Scope = "connection"
	ScopeRun            Scope = "run"
	ScopeStream         Scope = "stream"
	ScopeChat           Scope = "chat"
	ScopeTask           Scope = "task"
	ScopeModel          Scope = "model"
	ScopeProxy          Scope = "proxy"
	ScopeTool           Scope = "tool"
	ScopeFrontendSubmit Scope = "frontend_submit"
	ScopeResource       Scope = "resource"
	ScopeTerminal       Scope = "terminal"
	ScopeMemory         Scope = "memory"
	ScopeArchive        Scope = "archive"
	ScopeAutomation     Scope = "automation"
	ScopeSystem         Scope = "system"
)

const (
	CodeInvalidRequest        Code = "invalid_request"
	CodeInvalidPayload        Code = "invalid_payload"
	CodeMissingRequiredField  Code = "missing_required_field"
	CodeInvalidField          Code = "invalid_field"
	CodeMethodNotAllowed      Code = "method_not_allowed"
	CodeInvalidLocale         Code = "invalid_locale"
	CodeUnsupportedOperation  Code = "unsupported_operation"
	CodeTimeContractViolation Code = "time_contract_violation"

	CodeUnauthorized     Code = "unauthorized"
	CodeForbidden        Code = "forbidden"
	CodeAgentForbidden   Code = "agent_forbidden"
	CodeChannelForbidden Code = "channel_forbidden"

	CodeDuplicateID      Code = "duplicate_id"
	CodeDuplicateStream  Code = "duplicate_stream"
	CodeDuplicateObserve Code = "duplicate_observe"
	CodeTooManyStreams   Code = "too_many_streams"
	CodeTooManyObservers Code = "too_many_observers"
	CodeSeqExpired       Code = "seq_expired"
	CodeLegacySEQExpired Code = "SEQ_EXPIRED"

	CodeAgentNotFound            Code = "agent_not_found"
	CodeModelNotFound            Code = "model_not_found"
	CodeProviderNotConfigured    Code = "provider_not_configured"
	CodeModelRegistryUnavailable Code = "model_registry_unavailable"
	CodeAgentRegistryUnavailable Code = "agent_registry_unavailable"
	CodeConfigurationError       Code = "configuration_error"
	CodePlanningModeUnsupported  Code = "planning_mode_unsupported"
	CodeACPBridgeNotConfigured   Code = "acp_bridge_not_configured"
	CodeProxyConfigMissing       Code = "proxy_config_missing"

	CodeChatNotFound         Code = "chat_not_found"
	CodeRunNotFound          Code = "run_not_found"
	CodeActiveRunConflict    Code = "active_run_conflict"
	CodeRunAlreadyFinished   Code = "run_already_finished"
	CodeRunCancelled         Code = "run_cancelled"
	CodeRunTimeout           Code = "run_timeout"
	CodeEventBusUnavailable  Code = "event_bus_unavailable"
	CodeObserverAttachFailed Code = "observer_attach_failed"
	CodeStreamFailed         Code = "stream_failed"
	CodeRunError             Code = "run_error"
	CodeRunInterrupted       Code = "run_interrupted"

	CodeProviderRequestFailed         Code = "provider_request_failed"
	CodeProviderNetworkError          Code = "provider_network_error"
	CodeProviderTimeout               Code = "provider_timeout"
	CodeProviderAuthFailed            Code = "provider_auth_failed"
	CodeProviderPermissionDenied      Code = "provider_permission_denied"
	CodeProviderQuotaExhausted        Code = "provider_quota_exhausted"
	CodeProviderRateLimited           Code = "provider_rate_limited"
	CodeProviderModelNotFound         Code = "provider_model_not_found"
	CodeProviderContextLengthExceeded Code = "provider_context_length_exceeded"
	CodeProviderContentFilter         Code = "provider_content_filter"
	CodeProviderBadRequest            Code = "provider_bad_request"
	CodeProviderBadResponse           Code = "provider_bad_response"
	CodeProviderUnavailable           Code = "provider_unavailable"
	CodeProviderStreamFailed          Code = "provider_stream_failed"
	CodeProviderStreamInvalid         Code = "provider_stream_invalid"

	CodeProxyRequestFailed        Code = "proxy_request_failed"
	CodeProxyUpstreamError        Code = "proxy_upstream_error"
	CodeProxyTimeout              Code = "proxy_timeout"
	CodeProxyBadResponse          Code = "proxy_bad_response"
	CodeProxyStreamingUnsupported Code = "proxy_streaming_unsupported"

	CodeToolNotFound           Code = "tool_not_found"
	CodeToolFailed             Code = "tool_failed"
	CodeToolTimeout            Code = "tool_timeout"
	CodeToolArgsInvalid        Code = "tool_args_invalid"
	CodeToolCallsExceeded      Code = "tool_calls_exceeded"
	CodeExternalToolCallFailed Code = "external_tool_call_failed"
	CodeMCPCallFailed          Code = "mcp_call_failed"
	CodeSubAgentFailed         Code = "sub_agent_failed"
	CodeTaskFailed             Code = "task_failed"
	CodeTaskExecutionError     Code = "task_execution_error"
	CodePlanContextUnavailable Code = "plan_context_unavailable"

	CodeBudgetExceeded                   Code = "budget_exceeded"
	CodeModelCallsExceeded               Code = "model_calls_exceeded"
	CodePolicyDenied                     Code = "policy_denied"
	CodeHitlRejected                     Code = "hitl_rejected"
	CodeHitlRejectedWithFeedback         Code = "hitl_rejected_with_feedback"
	CodeHitlTimeout                      Code = "hitl_timeout"
	CodeApprovalTimeout                  Code = "approval_timeout"
	CodeUserDismissed                    Code = "user_dismissed"
	CodeFrontendSubmitTimeout            Code = "frontend_submit_timeout"
	CodeFrontendSubmitInvalidPayload     Code = "frontend_submit_invalid_payload"
	CodeFrontendToolHandlerNotRegistered Code = "frontend_tool_handler_not_registered"

	CodeResourceNotFound           Code = "resource_not_found"
	CodeResourceForbidden          Code = "resource_forbidden"
	CodeResourceTicketRequired     Code = "resource_ticket_required"
	CodeResourceTicketChatMismatch Code = "resource_ticket_chat_mismatch"
	CodeResourceReadFailed         Code = "resource_read_failed"
	CodeResourcePushFailed         Code = "resource_push_failed"
	CodeUploadFailed               Code = "upload_failed"
	CodeDownloadFailed             Code = "download_failed"
	CodeInvalidUploadMetadata      Code = "invalid_upload_metadata"
	CodeToolResultNotFound         Code = "tool_result_not_found"
	CodeToolResultForbidden        Code = "tool_result_forbidden"
	CodeToolResultAccessDenied     Code = "tool_result_access_denied"
	CodeFileHistoryUnavailable     Code = "file_history_unavailable"
	CodeFileHistoryNotFound        Code = "file_history_not_found"
	CodeInvalidFileHistoryRequest  Code = "invalid_file_history_request"

	CodeTerminalUnavailable Code = "terminal_unavailable"
	CodeTerminalNotFound    Code = "terminal_not_found"
	CodeTerminalUnsupported Code = "terminal_unsupported"
	CodeUnsupported         Code = "unsupported"

	CodeMemoryDisabled                 Code = "memory_disabled"
	CodeMemoryStoreUnavailable         Code = "memory_store_unavailable"
	CodeMemoryHistoryUnavailable       Code = "memory_history_unavailable"
	CodeMemoryNotFound                 Code = "memory_not_found"
	CodeEmbeddingProviderNotConfigured Code = "embedding_provider_not_configured"
	CodeMemoryOperationFailed          Code = "memory_operation_failed"

	CodeArchiveUnavailable     Code = "archive_unavailable"
	CodeArchiveNotFound        Code = "archive_not_found"
	CodeArchiveOperationFailed Code = "archive_operation_failed"

	CodeAutomationUnavailable               Code = "automation_unavailable"
	CodeAutomationNotFound                  Code = "automation_not_found"
	CodeAutomationInvalid                   Code = "automation_invalid"
	CodeAutomationExecutionStoreUnavailable Code = "automation_execution_store_unavailable"
	CodeAutomationIDAllocateFailed          Code = "automation_id_allocate_failed"

	CodeInternalError                  Code = "internal_error"
	CodeServiceUnavailable             Code = "service_unavailable"
	CodeUnavailable                    Code = "unavailable"
	CodeStorageFailed                  Code = "storage_failed"
	CodeChatStoreUnavailable           Code = "chat_store_unavailable"
	CodeSkillCandidateStoreUnavailable Code = "skill_candidate_store_unavailable"
	CodeNotImplemented                 Code = "not_implemented"
	CodeNotFound                       Code = "not_found"
	CodeTimeout                        Code = "timeout"
)
