package chat

import (
	"database/sql"
	"fmt"
	"path/filepath"

	_ "modernc.org/sqlite"
)

// ---------------------------------------------------------------------------
// SQLite chat index
// ---------------------------------------------------------------------------

func (s *FileStore) initDB() error {
	dbPath := filepath.Join(s.root, "chats.db")
	db, err := sql.Open("sqlite", dbPath)
	if err != nil {
		return fmt.Errorf("open chats.db: %w", err)
	}
	s.db = db

	_, err = db.Exec(`
		CREATE TABLE IF NOT EXISTS CHATS (
			CHAT_ID_          TEXT PRIMARY KEY,
			CHAT_NAME_        TEXT NOT NULL,
			OWNER_TYPE_       TEXT NOT NULL DEFAULT '',
			AGENT_KEY_        TEXT NOT NULL DEFAULT '',
			TEAM_ID_          TEXT,
			SOURCE_           TEXT NOT NULL DEFAULT '',
			SOURCE_CHANNEL_   TEXT NOT NULL DEFAULT '',
			CREATED_AT_       INTEGER NOT NULL,
			UPDATED_AT_       INTEGER NOT NULL,
			LAST_RUN_AT_      INTEGER NOT NULL DEFAULT 0,
			LAST_RUN_ID_      TEXT NOT NULL DEFAULT '',
			LAST_RUN_CONTENT_ TEXT NOT NULL DEFAULT '',
			READ_RUN_ID_      TEXT NOT NULL DEFAULT '',
			READ_AT_          INTEGER,
			USAGE_PROMPT_TOKENS_ INTEGER NOT NULL DEFAULT 0,
			USAGE_COMPLETION_TOKENS_ INTEGER NOT NULL DEFAULT 0,
			USAGE_TOTAL_TOKENS_ INTEGER NOT NULL DEFAULT 0,
			USAGE_CACHED_TOKENS_ INTEGER NOT NULL DEFAULT 0,
			USAGE_REASONING_TOKENS_ INTEGER NOT NULL DEFAULT 0,
			USAGE_PROMPT_CACHE_HIT_TOKENS_ INTEGER NOT NULL DEFAULT 0,
			USAGE_PROMPT_CACHE_MISS_TOKENS_ INTEGER NOT NULL DEFAULT 0,
			USAGE_ESTIMATED_COST_CURRENCY_ TEXT NOT NULL DEFAULT '',
			USAGE_ESTIMATED_COST_INPUT_CACHE_HIT_ REAL NOT NULL DEFAULT 0,
			USAGE_ESTIMATED_COST_INPUT_CACHE_MISS_ REAL NOT NULL DEFAULT 0,
			USAGE_ESTIMATED_COST_OUTPUT_ REAL NOT NULL DEFAULT 0,
			USAGE_ESTIMATED_COST_TOTAL_ REAL NOT NULL DEFAULT 0,
			USAGE_LLM_CHAT_COMPLETION_COUNT_ INTEGER NOT NULL DEFAULT 0,
			USAGE_TOOL_CALL_COUNT_ INTEGER NOT NULL DEFAULT 0,
			USAGE_FIRST_TOKEN_LATENCY_TOTAL_MS_ INTEGER NOT NULL DEFAULT 0,
			USAGE_FIRST_TOKEN_LATENCY_COUNT_ INTEGER NOT NULL DEFAULT 0,
			USAGE_GENERATION_DURATION_MS_ INTEGER NOT NULL DEFAULT 0,
			AWAITING_ID_ TEXT NOT NULL DEFAULT '',
			AWAITING_RUN_ID_ TEXT NOT NULL DEFAULT '',
			AWAITING_MODE_ TEXT NOT NULL DEFAULT '',
			AWAITING_CREATED_AT_ INTEGER NOT NULL DEFAULT 0
		);
		CREATE INDEX IF NOT EXISTS IDX_CHATS_LAST_RUN_ID_ ON CHATS(LAST_RUN_ID_);
		CREATE INDEX IF NOT EXISTS IDX_CHATS_AGENT_KEY_ ON CHATS(AGENT_KEY_);
		CREATE TABLE IF NOT EXISTS RUNS (
			RUN_ID_                  TEXT PRIMARY KEY,
			CHAT_ID_                 TEXT NOT NULL,
			OWNER_TYPE_              TEXT NOT NULL DEFAULT '',
			AGENT_KEY_               TEXT NOT NULL DEFAULT '',
			TEAM_ID_                 TEXT,
			INITIAL_MESSAGE_         TEXT NOT NULL DEFAULT '',
			ASSISTANT_TEXT_          TEXT NOT NULL DEFAULT '',
			FINISH_REASON_           TEXT NOT NULL DEFAULT '',
			STARTED_AT_              INTEGER NOT NULL DEFAULT 0,
			COMPLETED_AT_            INTEGER NOT NULL,
			USAGE_PROMPT_TOKENS_     INTEGER NOT NULL DEFAULT 0,
			USAGE_COMPLETION_TOKENS_ INTEGER NOT NULL DEFAULT 0,
			USAGE_TOTAL_TOKENS_      INTEGER NOT NULL DEFAULT 0,
			USAGE_CACHED_TOKENS_     INTEGER NOT NULL DEFAULT 0,
			USAGE_REASONING_TOKENS_  INTEGER NOT NULL DEFAULT 0,
			USAGE_PROMPT_CACHE_HIT_TOKENS_  INTEGER NOT NULL DEFAULT 0,
			USAGE_PROMPT_CACHE_MISS_TOKENS_ INTEGER NOT NULL DEFAULT 0,
			USAGE_ESTIMATED_COST_CURRENCY_ TEXT NOT NULL DEFAULT '',
			USAGE_ESTIMATED_COST_INPUT_CACHE_HIT_ REAL NOT NULL DEFAULT 0,
			USAGE_ESTIMATED_COST_INPUT_CACHE_MISS_ REAL NOT NULL DEFAULT 0,
			USAGE_ESTIMATED_COST_OUTPUT_ REAL NOT NULL DEFAULT 0,
			USAGE_ESTIMATED_COST_TOTAL_ REAL NOT NULL DEFAULT 0,
			USAGE_MODEL_KEY_ TEXT NOT NULL DEFAULT '',
			USAGE_LLM_CHAT_COMPLETION_COUNT_ INTEGER NOT NULL DEFAULT 0,
			USAGE_TOOL_CALL_COUNT_ INTEGER NOT NULL DEFAULT 0,
			USAGE_FIRST_TOKEN_LATENCY_TOTAL_MS_ INTEGER NOT NULL DEFAULT 0,
			USAGE_FIRST_TOKEN_LATENCY_COUNT_ INTEGER NOT NULL DEFAULT 0,
			USAGE_GENERATION_DURATION_MS_ INTEGER NOT NULL DEFAULT 0,
			FEEDBACK_TYPE_           TEXT NOT NULL DEFAULT '',
			FEEDBACK_COMMENT_        TEXT NOT NULL DEFAULT '',
			FEEDBACK_AT_             INTEGER NOT NULL DEFAULT 0
		);
		CREATE INDEX IF NOT EXISTS IDX_RUNS_CHAT_ID_ ON RUNS(CHAT_ID_);
	`)
	if err != nil {
		return fmt.Errorf("create chats table: %w", err)
	}

	s.migrateRunOwnerColumns()
	s.migrateAddUsageColumns()
	if err := s.migrateAwaitingColumns(); err != nil {
		return err
	}
	if err := s.migrateReadStateColumns(); err != nil {
		return err
	}
	s.migrateSourceColumn()
	s.migrateSourceChannelColumn()
	s.migrateLastRunAtColumn()
	s.migrateDetailedUsageColumns()
	return nil
}

// migrateLastRunAtColumn intentionally leaves existing rows at the schema
// default (zero). Historical records are not backfilled from run IDs, run
// rows, or updatedAt: public archive reads will reject them under the strict
// time contract instead of silently inventing a last-run instant.
func (s *FileStore) migrateLastRunAtColumn() {
	_, _ = s.db.Exec("ALTER TABLE CHATS ADD COLUMN LAST_RUN_AT_ INTEGER NOT NULL DEFAULT 0")
}

func (s *FileStore) migrateRunOwnerColumns() {
	_, _ = s.db.Exec("ALTER TABLE CHATS ADD COLUMN OWNER_TYPE_ TEXT NOT NULL DEFAULT ''")
	_, _ = s.db.Exec("ALTER TABLE RUNS ADD COLUMN OWNER_TYPE_ TEXT NOT NULL DEFAULT ''")
	_, _ = s.db.Exec("ALTER TABLE RUNS ADD COLUMN TEAM_ID_ TEXT")
	_, _ = s.db.Exec(`UPDATE CHATS SET OWNER_TYPE_=CASE
		WHEN TRIM(COALESCE(AGENT_KEY_,''))='' AND TRIM(COALESCE(TEAM_ID_,''))<>'' THEN 'team'
		ELSE 'agent' END
		WHERE TRIM(COALESCE(OWNER_TYPE_,''))=''`)
	_, _ = s.db.Exec(`UPDATE RUNS SET TEAM_ID_=(SELECT TEAM_ID_ FROM CHATS WHERE CHATS.CHAT_ID_=RUNS.CHAT_ID_)
		WHERE TRIM(COALESCE(TEAM_ID_,''))=''`)
	_, _ = s.db.Exec(`UPDATE RUNS SET OWNER_TYPE_=COALESCE((SELECT CASE
		WHEN TRIM(COALESCE(CHATS.OWNER_TYPE_,''))<>'' THEN CHATS.OWNER_TYPE_
		WHEN TRIM(COALESCE(CHATS.AGENT_KEY_,''))='' AND TRIM(COALESCE(CHATS.TEAM_ID_,''))<>'' THEN 'team'
		ELSE 'agent' END FROM CHATS WHERE CHATS.CHAT_ID_=RUNS.CHAT_ID_), 'agent')
		WHERE TRIM(COALESCE(OWNER_TYPE_,''))=''`)
}

func (s *FileStore) migrateAddUsageColumns() {
	for _, col := range []string{"USAGE_PROMPT_TOKENS_", "USAGE_COMPLETION_TOKENS_", "USAGE_TOTAL_TOKENS_"} {
		_, _ = s.db.Exec(fmt.Sprintf("ALTER TABLE CHATS ADD COLUMN %s INTEGER NOT NULL DEFAULT 0", col))
	}
}

func (s *FileStore) migrateDetailedUsageColumns() {
	intColumns := []string{
		"USAGE_CACHED_TOKENS_",
		"USAGE_REASONING_TOKENS_",
		"USAGE_PROMPT_CACHE_HIT_TOKENS_",
		"USAGE_PROMPT_CACHE_MISS_TOKENS_",
		"USAGE_LLM_CHAT_COMPLETION_COUNT_",
		"USAGE_TOOL_CALL_COUNT_",
		"USAGE_FIRST_TOKEN_LATENCY_TOTAL_MS_",
		"USAGE_FIRST_TOKEN_LATENCY_COUNT_",
		"USAGE_GENERATION_DURATION_MS_",
	}
	textColumns := []string{
		"USAGE_ESTIMATED_COST_CURRENCY_",
	}
	realColumns := []string{
		"USAGE_ESTIMATED_COST_INPUT_CACHE_HIT_",
		"USAGE_ESTIMATED_COST_INPUT_CACHE_MISS_",
		"USAGE_ESTIMATED_COST_OUTPUT_",
		"USAGE_ESTIMATED_COST_TOTAL_",
	}
	for _, table := range []string{"CHATS", "RUNS"} {
		for _, col := range intColumns {
			_, _ = s.db.Exec(fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s INTEGER NOT NULL DEFAULT 0", table, col))
		}
		for _, col := range textColumns {
			_, _ = s.db.Exec(fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s TEXT NOT NULL DEFAULT ''", table, col))
		}
		for _, col := range realColumns {
			_, _ = s.db.Exec(fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s REAL NOT NULL DEFAULT 0", table, col))
		}
	}
	_, _ = s.db.Exec("ALTER TABLE RUNS ADD COLUMN USAGE_MODEL_KEY_ TEXT NOT NULL DEFAULT ''")
}

func (s *FileStore) migrateSourceChannelColumn() {
	_, _ = s.db.Exec("ALTER TABLE CHATS ADD COLUMN SOURCE_CHANNEL_ TEXT NOT NULL DEFAULT ''")
}

func (s *FileStore) migrateSourceColumn() {
	_, _ = s.db.Exec("ALTER TABLE CHATS ADD COLUMN SOURCE_ TEXT NOT NULL DEFAULT ''")
}

func (s *FileStore) migrateAwaitingColumns() error {
	for _, stmt := range []string{
		"ALTER TABLE CHATS ADD COLUMN AWAITING_ID_ TEXT NOT NULL DEFAULT ''",
		"ALTER TABLE CHATS ADD COLUMN AWAITING_RUN_ID_ TEXT NOT NULL DEFAULT ''",
		"ALTER TABLE CHATS ADD COLUMN AWAITING_MODE_ TEXT NOT NULL DEFAULT ''",
		"ALTER TABLE CHATS ADD COLUMN AWAITING_CREATED_AT_ INTEGER NOT NULL DEFAULT 0",
	} {
		_, _ = s.db.Exec(stmt)
	}
	return nil
}

func (s *FileStore) migrateReadStateColumns() error {
	_, _ = s.db.Exec("ALTER TABLE CHATS ADD COLUMN READ_RUN_ID_ TEXT NOT NULL DEFAULT ''")
	_, err := s.db.Exec("CREATE INDEX IF NOT EXISTS IDX_CHATS_AGENT_KEY_ ON CHATS(AGENT_KEY_)")
	return err
}

func nilIfEmpty(s string) *string {
	if s == "" {
		return nil
	}
	return &s
}
